/**
 * Generates the OKLab-similarity palette permutation shared by the web editor and
 * the Java mod, and writes it to BOTH languages so the two stay byte-identical:
 *   - web/src/palette-perm.ts               (PERM / INV_PERM Uint8Array + CRC32)
 *   - src/main/java/.../PalettePermutation.java
 *
 * Rationale: map-colour bytes are palette *indices* (arbitrary labels), so a video
 * codec's spatial/temporal prediction is weak on them.  Reordering the palette so
 * that numerically-adjacent indices are visually close (small OKLab distance) makes
 * lossless AV1's prediction residuals small → smaller output.  The permutation is a
 * bijection over all 256 byte values (frames may legitimately contain any byte,
 * including unobtainable shade-3 in all-shades art), so every byte round-trips.
 *
 * Ordering: greedy nearest-neighbour open path in OKLab — start at the darkest valid
 * colour, repeatedly append the nearest unused valid colour (tie-break ascending
 * mapByte for determinism).  Invalid/reserved bytes are appended afterwards in
 * ascending order, filling indices up to 255.
 *
 * Run (no extra dependency needed):
 *   node --experimental-strip-types web/scripts/gen-palette-perm.ts
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { MC_PALETTE, IS_VALID } from '../src/palette.ts';
import { rgbIntToOklab, oklabDistSq } from '../src/oklab.ts';

const here = dirname(fileURLToPath(import.meta.url));

// ─── Build the ordering ─────────────────────────────────────────────────────────

const lab: Array<[number, number, number]> = new Array(256);
for (let b = 0; b < 256; b++) lab[b] = rgbIntToOklab(MC_PALETTE[b]);

const validBytes: number[] = [];
for (let b = 0; b < 256; b++) if (IS_VALID[b]) validBytes.push(b);

// Start at the darkest valid colour (min L), tie-break ascending byte.
let start = validBytes[0];
for (const b of validBytes) if (lab[b][0] < lab[start][0]) start = b;

const used = new Uint8Array(256);
const order: number[] = [];
let cur = start;
used[cur] = 1;
order.push(cur);
for (let n = 1; n < validBytes.length; n++) {
  let best = -1;
  let bestD = Infinity;
  for (const b of validBytes) {
    if (used[b]) continue;
    const d = oklabDistSq(lab[cur][0], lab[cur][1], lab[cur][2], lab[b][0], lab[b][1], lab[b][2]);
    if (d < bestD || (d === bestD && (best === -1 || b < best))) { bestD = d; best = b; }
  }
  used[best] = 1;
  order.push(best);
  cur = best;
}

// Append invalid/reserved bytes in ascending order to complete the bijection.
for (let b = 0; b < 256; b++) if (!IS_VALID[b]) order.push(b);

if (order.length !== 256) throw new Error(`order length ${order.length} != 256`);

// INV_PERM[permIndex] = mapByte ; PERM[mapByte] = permIndex
const INV_PERM = Uint8Array.from(order);
const PERM = new Uint8Array(256);
for (let i = 0; i < 256; i++) PERM[INV_PERM[i]] = i;

// Bijection sanity check.
const seen = new Uint8Array(256);
for (let i = 0; i < 256; i++) {
  if (seen[INV_PERM[i]]) throw new Error(`duplicate mapByte ${INV_PERM[i]} in permutation`);
  seen[INV_PERM[i]] = 1;
  if (PERM[INV_PERM[i]] !== i) throw new Error('PERM/INV_PERM not inverse');
}

// ─── CRC32 (matches manifest.ts crc32) ──────────────────────────────────────────

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i];
    for (let k = 0; k < 8; k++) crc = (crc & 1) ? (0xedb88320 ^ (crc >>> 1)) : (crc >>> 1);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
const CRC = crc32(INV_PERM);

// ─── Emit ────────────────────────────────────────────────────────────────────────

function rows(arr: Uint8Array): string {
  const out: string[] = [];
  for (let i = 0; i < 256; i += 16) {
    out.push('  ' + Array.from(arr.subarray(i, i + 16)).map(n => String(n).padStart(3, ' ')).join(', ') + ',');
  }
  return out.join('\n');
}

const tsFile = `/**
 * OKLab-similarity palette permutation — GENERATED by web/scripts/gen-palette-perm.ts.
 * DO NOT EDIT BY HAND.  Regenerate with:
 *   node --experimental-strip-types web/scripts/gen-palette-perm.ts
 *
 * PERM[mapByte]   → permIndex (apply before AV1 encode)
 * INV_PERM[permIndex] → mapByte (apply after AV1 decode)
 * Kept byte-identical with PalettePermutation.java (CRC32 asserted in tests).
 */

/** CRC32 of INV_PERM — parity check against the Java table. */
export const PERM_CRC32 = 0x${CRC.toString(16).padStart(8, '0')};

/** mapByte → permutation index. */
export const PERM: Uint8Array = new Uint8Array([
${rows(PERM)}
]);

/** permutation index → mapByte. */
export const INV_PERM: Uint8Array = new Uint8Array([
${rows(INV_PERM)}
]);
`;

function javaRows(arr: Uint8Array): string {
  const out: string[] = [];
  for (let i = 0; i < 256; i += 16) {
    out.push('        ' + Array.from(arr.subarray(i, i + 16))
      .map(n => String(n > 127 ? n - 256 : n).padStart(4, ' ')).join(', ') + ',');
  }
  return out.join('\n');
}

const javaFile = `package net.zerohpminecraft;

/**
 * OKLab-similarity palette permutation — GENERATED by web/scripts/gen-palette-perm.ts.
 * DO NOT EDIT BY HAND.  Kept byte-identical with web/src/palette-perm.ts.
 *
 * PERM[mapByte & 0xFF]       -> permIndex (encode side; web only)
 * INV_PERM[permIndex & 0xFF] -> mapByte   (decode side; applied after AV1 decode)
 */
public final class PalettePermutation {
    private PalettePermutation() {}

    /** CRC32 of INV_PERM (unsigned) — parity check against the TypeScript table. */
    public static final long PERM_CRC32 = 0x${CRC.toString(16).padStart(8, '0')}L;

    /** mapByte -> permutation index. */
    public static final byte[] PERM = {
${javaRows(PERM)}
    };

    /** permutation index -> mapByte. */
    public static final byte[] INV_PERM = {
${javaRows(INV_PERM)}
    };
}
`;

// ─── Palette RGB entries (for lossy-colour nearest-match, shared web + mod) ──────
// {mapByte, r, g, b} per valid colour, in ascending mapByte order.  Committed to Java so the
// mod's nearest-match uses the EXACT same palette RGB as the web preview (identical results).
const entries: number[] = [];
for (let b = 0; b < 256; b++) {
  if (!IS_VALID[b]) continue;
  const p = MC_PALETTE[b];
  entries.push(b, (p >> 16) & 0xff, (p >> 8) & 0xff, p & 0xff);
}
function javaBytes(arr: number[]): string {
  const out: string[] = [];
  for (let i = 0; i < arr.length; i += 16) {
    out.push('        ' + arr.slice(i, i + 16)
      .map(n => String(n > 127 ? n - 256 : n).padStart(4, ' ')).join(', ') + ',');
  }
  return out.join('\n');
}
const paletteJava = `package net.zerohpminecraft;

/**
 * Map palette RGB entries — GENERATED by web/scripts/gen-palette-perm.ts from palette.ts.
 * DO NOT EDIT BY HAND.  Flat {mapByte, r, g, b} quads for every valid colour, used to
 * re-quantise lossy-colour AV1 frames to map bytes.  Byte-identical to the web MC_PALETTE so
 * the in-game result matches the export preview exactly.
 */
public final class MapPalette {
    private MapPalette() {}

    /** ${entries.length / 4} entries, each 4 bytes: mapByte, r, g, b. */
    public static final byte[] RGB_ENTRIES = {
${javaBytes(entries)}
    };
}
`;

const tsPath   = resolve(here, '../src/palette-perm.ts');
const javaPath = resolve(here, '../../src/main/java/net/zerohpminecraft/PalettePermutation.java');
const palPath  = resolve(here, '../../src/main/java/net/zerohpminecraft/MapPalette.java');
writeFileSync(tsPath, tsFile);
writeFileSync(javaPath, javaFile);
writeFileSync(palPath, paletteJava);

console.log(`PERM_CRC32 = 0x${CRC.toString(16).padStart(8, '0')}`);
console.log(`valid colours ordered: ${validBytes.length}, start mapByte=${start}`);
console.log(`wrote ${tsPath}`);
console.log(`wrote ${javaPath}`);
