// Minecraft 1.21.4 map colour table — generated by /loominary dumppalette
// Index = (colorId << 2) | shadeId  (byte value used in MapState.colors)

// ─── Raw RGB data from dumppalette ───────────────────────────────────────────
// Null entries = unused/transparent (mapByte 0–3 and any gaps).

const _RGB: ([number, number, number] | null)[] = new Array(256).fill(null);
_RGB[4] = [89, 125, 39]; // colorId=1 shade=0
_RGB[5] = [109, 153, 48]; // colorId=1 shade=1
_RGB[6] = [127, 178, 56]; // colorId=1 shade=2
_RGB[7] = [67, 94, 29]; // colorId=1 shade=3
_RGB[8] = [174, 164, 115]; // colorId=2 shade=0
_RGB[9] = [213, 201, 140]; // colorId=2 shade=1
_RGB[10] = [247, 233, 163]; // colorId=2 shade=2
_RGB[11] = [130, 123, 86]; // colorId=2 shade=3
_RGB[12] = [140, 140, 140]; // colorId=3 shade=0
_RGB[13] = [171, 171, 171]; // colorId=3 shade=1
_RGB[14] = [199, 199, 199]; // colorId=3 shade=2
_RGB[15] = [105, 105, 105]; // colorId=3 shade=3
_RGB[16] = [180, 0, 0]; // colorId=4 shade=0
_RGB[17] = [220, 0, 0]; // colorId=4 shade=1
_RGB[18] = [255, 0, 0]; // colorId=4 shade=2
_RGB[19] = [135, 0, 0]; // colorId=4 shade=3
_RGB[20] = [112, 112, 180]; // colorId=5 shade=0
_RGB[21] = [138, 138, 220]; // colorId=5 shade=1
_RGB[22] = [160, 160, 255]; // colorId=5 shade=2
_RGB[23] = [84, 84, 135]; // colorId=5 shade=3
_RGB[24] = [117, 117, 117]; // colorId=6 shade=0
_RGB[25] = [144, 144, 144]; // colorId=6 shade=1
_RGB[26] = [167, 167, 167]; // colorId=6 shade=2
_RGB[27] = [88, 88, 88]; // colorId=6 shade=3
_RGB[28] = [0, 87, 0]; // colorId=7 shade=0
_RGB[29] = [0, 106, 0]; // colorId=7 shade=1
_RGB[30] = [0, 124, 0]; // colorId=7 shade=2
_RGB[31] = [0, 65, 0]; // colorId=7 shade=3
_RGB[32] = [180, 180, 180]; // colorId=8 shade=0
_RGB[33] = [220, 220, 220]; // colorId=8 shade=1
_RGB[34] = [255, 255, 255]; // colorId=8 shade=2
_RGB[35] = [135, 135, 135]; // colorId=8 shade=3
_RGB[36] = [115, 118, 129]; // colorId=9 shade=0
_RGB[37] = [141, 144, 158]; // colorId=9 shade=1
_RGB[38] = [164, 168, 184]; // colorId=9 shade=2
_RGB[39] = [86, 88, 97]; // colorId=9 shade=3
_RGB[40] = [106, 76, 54]; // colorId=10 shade=0
_RGB[41] = [130, 94, 66]; // colorId=10 shade=1
_RGB[42] = [151, 109, 77]; // colorId=10 shade=2
_RGB[43] = [79, 57, 40]; // colorId=10 shade=3
_RGB[44] = [79, 79, 79]; // colorId=11 shade=0
_RGB[45] = [96, 96, 96]; // colorId=11 shade=1
_RGB[46] = [112, 112, 112]; // colorId=11 shade=2
_RGB[47] = [59, 59, 59]; // colorId=11 shade=3
_RGB[48] = [45, 45, 180]; // colorId=12 shade=0
_RGB[49] = [55, 55, 220]; // colorId=12 shade=1
_RGB[50] = [64, 64, 255]; // colorId=12 shade=2
_RGB[51] = [33, 33, 135]; // colorId=12 shade=3
_RGB[52] = [100, 84, 50]; // colorId=13 shade=0
_RGB[53] = [123, 102, 62]; // colorId=13 shade=1
_RGB[54] = [143, 119, 72]; // colorId=13 shade=2
_RGB[55] = [75, 63, 38]; // colorId=13 shade=3
_RGB[56] = [180, 177, 172]; // colorId=14 shade=0
_RGB[57] = [220, 217, 211]; // colorId=14 shade=1
_RGB[58] = [255, 252, 245]; // colorId=14 shade=2
_RGB[59] = [135, 133, 129]; // colorId=14 shade=3
_RGB[60] = [152, 89, 36]; // colorId=15 shade=0
_RGB[61] = [186, 109, 44]; // colorId=15 shade=1
_RGB[62] = [216, 127, 51]; // colorId=15 shade=2
_RGB[63] = [114, 67, 27]; // colorId=15 shade=3
_RGB[64] = [125, 53, 152]; // colorId=16 shade=0
_RGB[65] = [153, 65, 186]; // colorId=16 shade=1
_RGB[66] = [178, 76, 216]; // colorId=16 shade=2
_RGB[67] = [94, 40, 114]; // colorId=16 shade=3
_RGB[68] = [72, 108, 152]; // colorId=17 shade=0
_RGB[69] = [88, 132, 186]; // colorId=17 shade=1
_RGB[70] = [102, 153, 216]; // colorId=17 shade=2
_RGB[71] = [54, 81, 114]; // colorId=17 shade=3
_RGB[72] = [161, 161, 36]; // colorId=18 shade=0
_RGB[73] = [197, 197, 44]; // colorId=18 shade=1
_RGB[74] = [229, 229, 51]; // colorId=18 shade=2
_RGB[75] = [121, 121, 27]; // colorId=18 shade=3
_RGB[76] = [89, 144, 17]; // colorId=19 shade=0
_RGB[77] = [109, 176, 21]; // colorId=19 shade=1
_RGB[78] = [127, 204, 25]; // colorId=19 shade=2
_RGB[79] = [67, 108, 13]; // colorId=19 shade=3
_RGB[80] = [170, 89, 116]; // colorId=20 shade=0
_RGB[81] = [208, 109, 142]; // colorId=20 shade=1
_RGB[82] = [242, 127, 165]; // colorId=20 shade=2
_RGB[83] = [128, 67, 87]; // colorId=20 shade=3
_RGB[84] = [53, 53, 53]; // colorId=21 shade=0
_RGB[85] = [65, 65, 65]; // colorId=21 shade=1
_RGB[86] = [76, 76, 76]; // colorId=21 shade=2
_RGB[87] = [40, 40, 40]; // colorId=21 shade=3
_RGB[88] = [108, 108, 108]; // colorId=22 shade=0
_RGB[89] = [132, 132, 132]; // colorId=22 shade=1
_RGB[90] = [153, 153, 153]; // colorId=22 shade=2
_RGB[91] = [81, 81, 81]; // colorId=22 shade=3
_RGB[92] = [53, 89, 108]; // colorId=23 shade=0
_RGB[93] = [65, 109, 132]; // colorId=23 shade=1
_RGB[94] = [76, 127, 153]; // colorId=23 shade=2
_RGB[95] = [40, 67, 81]; // colorId=23 shade=3
_RGB[96] = [89, 44, 125]; // colorId=24 shade=0
_RGB[97] = [109, 54, 153]; // colorId=24 shade=1
_RGB[98] = [127, 63, 178]; // colorId=24 shade=2
_RGB[99] = [67, 33, 94]; // colorId=24 shade=3
_RGB[100] = [36, 53, 125]; // colorId=25 shade=0
_RGB[101] = [44, 65, 153]; // colorId=25 shade=1
_RGB[102] = [51, 76, 178]; // colorId=25 shade=2
_RGB[103] = [27, 40, 94]; // colorId=25 shade=3
_RGB[104] = [72, 53, 36]; // colorId=26 shade=0
_RGB[105] = [88, 65, 44]; // colorId=26 shade=1
_RGB[106] = [102, 76, 51]; // colorId=26 shade=2
_RGB[107] = [54, 40, 27]; // colorId=26 shade=3
_RGB[108] = [72, 89, 36]; // colorId=27 shade=0
_RGB[109] = [88, 109, 44]; // colorId=27 shade=1
_RGB[110] = [102, 127, 51]; // colorId=27 shade=2
_RGB[111] = [54, 67, 27]; // colorId=27 shade=3
_RGB[112] = [108, 36, 36]; // colorId=28 shade=0
_RGB[113] = [132, 44, 44]; // colorId=28 shade=1
_RGB[114] = [153, 51, 51]; // colorId=28 shade=2
_RGB[115] = [81, 27, 27]; // colorId=28 shade=3
_RGB[116] = [17, 17, 17]; // colorId=29 shade=0
_RGB[117] = [21, 21, 21]; // colorId=29 shade=1
_RGB[118] = [25, 25, 25]; // colorId=29 shade=2
_RGB[119] = [13, 13, 13]; // colorId=29 shade=3
_RGB[120] = [176, 168, 54]; // colorId=30 shade=0
_RGB[121] = [215, 205, 66]; // colorId=30 shade=1
_RGB[122] = [250, 238, 77]; // colorId=30 shade=2
_RGB[123] = [132, 126, 40]; // colorId=30 shade=3
_RGB[124] = [64, 154, 150]; // colorId=31 shade=0
_RGB[125] = [79, 188, 183]; // colorId=31 shade=1
_RGB[126] = [92, 219, 213]; // colorId=31 shade=2
_RGB[127] = [48, 115, 112]; // colorId=31 shade=3
_RGB[128] = [52, 90, 180]; // colorId=32 shade=0
_RGB[129] = [63, 110, 220]; // colorId=32 shade=1
_RGB[130] = [74, 128, 255]; // colorId=32 shade=2
_RGB[131] = [39, 67, 135]; // colorId=32 shade=3
_RGB[132] = [0, 153, 40]; // colorId=33 shade=0
_RGB[133] = [0, 187, 50]; // colorId=33 shade=1
_RGB[134] = [0, 217, 58]; // colorId=33 shade=2
_RGB[135] = [0, 114, 30]; // colorId=33 shade=3
_RGB[136] = [91, 60, 34]; // colorId=34 shade=0
_RGB[137] = [111, 74, 42]; // colorId=34 shade=1
_RGB[138] = [129, 86, 49]; // colorId=34 shade=2
_RGB[139] = [68, 45, 25]; // colorId=34 shade=3
_RGB[140] = [79, 1, 0]; // colorId=35 shade=0
_RGB[141] = [96, 1, 0]; // colorId=35 shade=1
_RGB[142] = [112, 2, 0]; // colorId=35 shade=2
_RGB[143] = [59, 1, 0]; // colorId=35 shade=3
_RGB[144] = [147, 124, 113]; // colorId=36 shade=0
_RGB[145] = [180, 152, 138]; // colorId=36 shade=1
_RGB[146] = [209, 177, 161]; // colorId=36 shade=2
_RGB[147] = [110, 93, 85]; // colorId=36 shade=3
_RGB[148] = [112, 57, 25]; // colorId=37 shade=0
_RGB[149] = [137, 70, 31]; // colorId=37 shade=1
_RGB[150] = [159, 82, 36]; // colorId=37 shade=2
_RGB[151] = [84, 43, 19]; // colorId=37 shade=3
_RGB[152] = [105, 61, 76]; // colorId=38 shade=0
_RGB[153] = [128, 75, 93]; // colorId=38 shade=1
_RGB[154] = [149, 87, 108]; // colorId=38 shade=2
_RGB[155] = [78, 46, 57]; // colorId=38 shade=3
_RGB[156] = [79, 76, 97]; // colorId=39 shade=0
_RGB[157] = [96, 93, 119]; // colorId=39 shade=1
_RGB[158] = [112, 108, 138]; // colorId=39 shade=2
_RGB[159] = [59, 57, 73]; // colorId=39 shade=3
_RGB[160] = [131, 93, 25]; // colorId=40 shade=0
_RGB[161] = [160, 114, 31]; // colorId=40 shade=1
_RGB[162] = [186, 133, 36]; // colorId=40 shade=2
_RGB[163] = [98, 70, 19]; // colorId=40 shade=3
_RGB[164] = [72, 82, 37]; // colorId=41 shade=0
_RGB[165] = [88, 100, 45]; // colorId=41 shade=1
_RGB[166] = [103, 117, 53]; // colorId=41 shade=2
_RGB[167] = [54, 61, 28]; // colorId=41 shade=3
_RGB[168] = [112, 54, 55]; // colorId=42 shade=0
_RGB[169] = [138, 66, 67]; // colorId=42 shade=1
_RGB[170] = [160, 77, 78]; // colorId=42 shade=2
_RGB[171] = [84, 40, 41]; // colorId=42 shade=3
_RGB[172] = [40, 28, 24]; // colorId=43 shade=0
_RGB[173] = [49, 35, 30]; // colorId=43 shade=1
_RGB[174] = [57, 41, 35]; // colorId=43 shade=2
_RGB[175] = [30, 21, 18]; // colorId=43 shade=3
_RGB[176] = [95, 75, 69]; // colorId=44 shade=0
_RGB[177] = [116, 92, 84]; // colorId=44 shade=1
_RGB[178] = [135, 107, 98]; // colorId=44 shade=2
_RGB[179] = [71, 56, 51]; // colorId=44 shade=3
_RGB[180] = [61, 64, 64]; // colorId=45 shade=0
_RGB[181] = [75, 79, 79]; // colorId=45 shade=1
_RGB[182] = [87, 92, 92]; // colorId=45 shade=2
_RGB[183] = [46, 48, 48]; // colorId=45 shade=3
_RGB[184] = [86, 51, 62]; // colorId=46 shade=0
_RGB[185] = [105, 62, 75]; // colorId=46 shade=1
_RGB[186] = [122, 73, 88]; // colorId=46 shade=2
_RGB[187] = [64, 38, 46]; // colorId=46 shade=3
_RGB[188] = [53, 43, 64]; // colorId=47 shade=0
_RGB[189] = [65, 53, 79]; // colorId=47 shade=1
_RGB[190] = [76, 62, 92]; // colorId=47 shade=2
_RGB[191] = [40, 32, 48]; // colorId=47 shade=3
_RGB[192] = [53, 35, 24]; // colorId=48 shade=0
_RGB[193] = [65, 43, 30]; // colorId=48 shade=1
_RGB[194] = [76, 50, 35]; // colorId=48 shade=2
_RGB[195] = [40, 26, 18]; // colorId=48 shade=3
_RGB[196] = [53, 57, 29]; // colorId=49 shade=0
_RGB[197] = [65, 70, 36]; // colorId=49 shade=1
_RGB[198] = [76, 82, 42]; // colorId=49 shade=2
_RGB[199] = [40, 43, 22]; // colorId=49 shade=3
_RGB[200] = [100, 42, 32]; // colorId=50 shade=0
_RGB[201] = [122, 51, 39]; // colorId=50 shade=1
_RGB[202] = [142, 60, 46]; // colorId=50 shade=2
_RGB[203] = [75, 31, 24]; // colorId=50 shade=3
_RGB[204] = [26, 15, 11]; // colorId=51 shade=0
_RGB[205] = [31, 18, 13]; // colorId=51 shade=1
_RGB[206] = [37, 22, 16]; // colorId=51 shade=2
_RGB[207] = [19, 11, 8]; // colorId=51 shade=3
_RGB[208] = [133, 33, 34]; // colorId=52 shade=0
_RGB[209] = [163, 41, 42]; // colorId=52 shade=1
_RGB[210] = [189, 48, 49]; // colorId=52 shade=2
_RGB[211] = [100, 25, 25]; // colorId=52 shade=3
_RGB[212] = [104, 44, 68]; // colorId=53 shade=0
_RGB[213] = [127, 54, 83]; // colorId=53 shade=1
_RGB[214] = [148, 63, 97]; // colorId=53 shade=2
_RGB[215] = [78, 33, 51]; // colorId=53 shade=3
_RGB[216] = [64, 17, 20]; // colorId=54 shade=0
_RGB[217] = [79, 21, 25]; // colorId=54 shade=1
_RGB[218] = [92, 25, 29]; // colorId=54 shade=2
_RGB[219] = [48, 13, 15]; // colorId=54 shade=3
_RGB[220] = [15, 88, 94]; // colorId=55 shade=0
_RGB[221] = [18, 108, 115]; // colorId=55 shade=1
_RGB[222] = [22, 126, 134]; // colorId=55 shade=2
_RGB[223] = [11, 66, 70]; // colorId=55 shade=3
_RGB[224] = [40, 100, 98]; // colorId=56 shade=0
_RGB[225] = [50, 122, 120]; // colorId=56 shade=1
_RGB[226] = [58, 142, 140]; // colorId=56 shade=2
_RGB[227] = [30, 75, 74]; // colorId=56 shade=3
_RGB[228] = [60, 31, 43]; // colorId=57 shade=0
_RGB[229] = [74, 37, 53]; // colorId=57 shade=1
_RGB[230] = [86, 44, 62]; // colorId=57 shade=2
_RGB[231] = [45, 23, 32]; // colorId=57 shade=3
_RGB[232] = [14, 127, 93]; // colorId=58 shade=0
_RGB[233] = [17, 155, 114]; // colorId=58 shade=1
_RGB[234] = [20, 180, 133]; // colorId=58 shade=2
_RGB[235] = [10, 95, 70]; // colorId=58 shade=3
_RGB[236] = [70, 70, 70]; // colorId=59 shade=0
_RGB[237] = [86, 86, 86]; // colorId=59 shade=1
_RGB[238] = [100, 100, 100]; // colorId=59 shade=2
_RGB[239] = [52, 52, 52]; // colorId=59 shade=3
_RGB[240] = [152, 123, 103]; // colorId=60 shade=0
_RGB[241] = [186, 150, 126]; // colorId=60 shade=1
_RGB[242] = [216, 175, 147]; // colorId=60 shade=2
_RGB[243] = [114, 92, 77]; // colorId=60 shade=3
_RGB[244] = [89, 117, 105]; // colorId=61 shade=0
_RGB[245] = [109, 144, 129]; // colorId=61 shade=1
_RGB[246] = [127, 167, 150]; // colorId=61 shade=2
_RGB[247] = [67, 88, 79]; // colorId=61 shade=3

// ─── Derived exports (same interface as before) ───────────────────────────────

/** mapByte → packed 0xRRGGBB integer.  0 = transparent / invalid. */
export const MC_PALETTE = new Uint32Array(256);

/** 1 if this mapByte is a valid (non-null) colour (includes unobtainable shade 3). */
export const IS_VALID = new Uint8Array(256);

/** 1 if this mapByte is a legal obtainable colour (shades 0–2 only). */
export const IS_LEGAL = new Uint8Array(256);

for (let i = 0; i < 256; i++) {
  const rgb = _RGB[i];
  if (!rgb) continue;
  MC_PALETTE[i] = (rgb[0] << 16) | (rgb[1] << 8) | rgb[2];
  IS_VALID[i] = 1;
  if ((i & 3) !== 3) IS_LEGAL[i] = 1; // shade 3 is unobtainable
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

export type RGB = [r: number, g: number, b: number];

export function mapByteToRgb(mapByte: number): RGB {
  const p = _RGB[mapByte];
  return p ?? [0, 0, 0];
}

/**
 * Override palette entries from a future /loominary dumppalette run.
 * Accepts the same [mapByte, R, G, B] format the command emits.
 */
export function applyPaletteDump(entries: Array<[mapByte: number, r: number, g: number, b: number]>): void {
  for (const [b, r, g, bl] of entries) {
    _RGB[b] = [r, g, bl];
    MC_PALETTE[b] = (r << 16) | (g << 8) | bl;
    IS_VALID[b] = 1;
    IS_LEGAL[b] = (b & 3) !== 3 ? 1 : 0;
  }
}
